### ISSUE TITLE
Xcode  7.2 (7C68)

### ISSUE THREAD

**Issue by eiros** [chaingarden/DBSmartPanels#16]
Does not work (or install). Tried to Install within Alcatraz too. "Smart Panels..." option in the Xcode menu does not appear.

**Comment by jbeker** [comment]
I'm seeing the same thing. It worked right after I installed it, but after a few reloads of Xcode, it is gone from the Xcode menu.

**Comment by jbeker** [comment]
OK, to those who find this problem. this solution worked for me:

http://stackoverflow.com/a/24877680/603281

**Comment by chaingarden** [comment]
I'll try to get the compatibility UUID for Xcode 7.2 in for the plugin tonight or tomorrow, at which point it should start loading automatically I believe, if it was installed via Alcatraz.

**Comment by chaingarden** [comment]
I've pushed the Xcode 7.2 compatibility UUID so this should be resolved now. I believe Alcatraz automatically updates plugins on each load of Xcode so a restart of Xcode would probably get Smart Panels going again.
