### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ForrestAlfred** [chaingarden/DBSmartPanels#8]
Hiya, I'd love to have a navigation panel  auto-hide function, Could you add it to your newest DBSmartPanels?

**Comment by chaingarden** [comment]
Interesting...this isn't the first request for this...I'll take a look when I get back from vacation next month. :)

**Comment by ForrestAlfred** [comment]
:)，wonderful，have a nice vacation！

**Comment by chaingarden** [comment]
I've updated the plugin to include a navigation panel auto-hide function (disabled when you're on the Find tab). By default this option is disabled, but if you switch the (new) Auto-hiding dropdown to Aggressive, it will be enabled. Let me know what you think! It's taken me some getting used to, but I think I like it so far.

**Comment by ForrestAlfred** [comment]
Wonderful Plugin ! I am enjoying it, so neat, the woking space is, with the navigation area hidden ! 
Thanks for your effort !

**Comment by chaingarden** [comment]
I'm so glad to hear you like it! Let me know if you run into any problems or would like any tweaks. :)
