### ISSUE TITLE
Add UUID for Xcode 6.3.2

### ISSUE THREAD

**Issue by winkelsdorf** [chaingarden/DBSmartPanels#9]
Missing <string>E969541F-E6F9-4D25-8158-72DC3545A6C6</string>

**Comment by winkelsdorf** [comment]
Quick note: Even after adding UUID plugin is not showing up after restart of Xcode.

**Comment by chaingarden** [comment]
@winkelsdorf: Running it locally, I find that the menu option is no longer there (due to [NSApp mainMenu] now returning nil), but the functionality does work. Is this your experience as well?

**Comment by winkelsdorf** [comment]
@chaingarden Exactly, I can confirm the functionality to be working as good as always, just the menu option is not showing up.

**Comment by chaingarden** [comment]
I've added a 1 second delay for adding the preferences menu, as it seems the Xcode application loading process has changed a bit, and the mainMenu doesn't get instantiated prior to the plugin starting up.

Seems to be all good now! Let me know if otherwise.

I'll be on vacation the next couple weeks without a laptop, so hopefully Apple doesn't release Xcode 6.3.3 with a new incompatibility. ;)

**Comment by winkelsdorf** [comment]
Just fetched your latest commit, working like a charm again now :)

Keep up the good work, but for now stop coding and enjoy your vacaction 😀

Haha, yes, hopefully not. Well at least it would be easily fixable with a bit experience ;)

**Comment by chaingarden** [comment]
Thanks for the confirmation Frederik! Haha, last minute coding is fun,
especially when working in officially-unsupported plugin environments... ;)

**Comment by winkelsdorf** [comment]
Riiiiiight, it is :) But better not call if officially-unsupported, but Cutting Edge OpenSource ;)

I owe you a beer next time I'm the Bay Area, likely 2016, going to visit some colleague at work and friends in SF :)

**Comment by chaingarden** [comment]
Sounds good to me!

**Comment by chaingarden** [comment]
@winkelsdorf I've updated the plugin to include a navigation panel auto-hide function (disabled when you're on the Find tab). By default this option is disabled, but if you switch the (new) Auto-hiding dropdown to Aggressive, it will be enabled. Let me know what you think! It's taken me some getting used to, but I think I like it so far.

**Comment by winkelsdorf** [comment]
@chaingarden Woohoo, I love it! That's perfect for the rMBP screen :+1: It's a lot better when trying to focus on what you're doing now if the navigation panel is hidden, that said having it done automatically is just pure fun. And bringing back the utilities for Storyboards is working like a charm too. Next to cocoapods/carthage this is one of my favorite Plugins now, really!

btw/off topic: Can you recommend a freelancer being available right now for a paid estimated 10 hrs to 20 hrs counsel with a Swift Project? Remote working during SF after hours is fine. Feel free to drop a mail :)

**Comment by chaingarden** [comment]
@winkelsdorf Sorry for the late reply...I don't know anyone currently taking on side work...hope you were able to fill the need!
